import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { expect, test } from "vitest";

const testDir = path.dirname(fileURLToPath(import.meta.url));
const contributeDir = path.join(testDir, "..", "src", "app", "contribute");

test("검토 큐의 제안 보기는 해당 용어를 제안 검토 화면에 전달한다", () => {
  const queuePanel = readFileSync(path.join(contributeDir, "review-queue-panel.tsx"), "utf8");
  const page = readFileSync(path.join(contributeDir, "page.tsx"), "utf8");
  const fieldsPage = readFileSync(path.join(contributeDir, "fields", "page.tsx"), "utf8");
  const reviewPanel = readFileSync(path.join(contributeDir, "agent-review-panel.tsx"), "utf8");
  const queueTable = readFileSync(path.join(contributeDir, "contribution-queue-table.tsx"), "utf8");
  const classificationPanel = readFileSync(path.join(contributeDir, "classification-review-panel.tsx"), "utf8");
  const definitionPanel = readFileSync(path.join(contributeDir, "definition-review-panel.tsx"), "utf8");

  expect(queuePanel).toContain("tab=agent&termId=${encodeURIComponent(item.termId)}");
  expect(queuePanel).toContain("처리 재개");
  expect(queuePanel).toContain("다시 요청");
  expect(page).toContain('const PRIMARY_TABS = [');
  expect(page).toContain('{ key: "duplicates", label: "중복 후보 검토", href: "/contribute?tab=duplicates" }');
  expect(page).toContain('redirect(`/contribute/fields?${fieldParams.toString()}`)');
  expect(page).toContain('href="/contribute?tab=queue"');
  expect(page).toContain('href="/contribute/fields"');
  expect(page).not.toContain("ClassificationReviewPanel");
  expect(page).not.toContain("DefinitionReviewPanel");
  expect(page).toContain('const contributionLimit = tab === "agent" ? AGENT_REVIEW_LIST_LIMIT : 60;');
  expect(page).toContain('listContributionTerms(contributionLimit, user.id, selectedTermId, { includePrepared: true, preservePreferredOrder: true })');
  expect(page).not.toContain('prepareAutoReviews(missing.map((term) => term.id))');
  expect(page).not.toContain('자동·수동 AI 검토의 진행 상태를 함께 확인합니다.');
  expect(page).not.toContain('tab === "agent" ? "현재 값과 제안을 비교한 뒤 필요한 변경만 승인하세요."');
  expect(page).toContain("ContributionQueueTable");
  expect(fieldsPage).toContain('current="field-completion" roomy>');
  expect(fieldsPage).toContain('const FIELD_ITEMS');
  expect(fieldsPage).toContain('aria-label="필드 보완 작업" className="mb-6 flex min-w-0 overflow-x-auto overflow-y-hidden border-b border-line"');
  expect(fieldsPage).toContain('field === "definition" ?');
  expect(fieldsPage).toContain("ClassificationReviewPanel");
  expect(fieldsPage).toContain("listClassificationReviewCandidates(classificationKind, 200, query)");
  expect(fieldsPage).toContain('basePath="/contribute/fields"');
  const fieldsOverviewIndex = fieldsPage.indexOf("function FieldOverview()");
  const fieldsNavIndex = fieldsPage.indexOf('<nav aria-label="필드 보완 작업"');
  expect(fieldsOverviewIndex).toBeGreaterThan(fieldsNavIndex);
  expect(fieldsPage).toContain('import { HelpTip } from "@/components/help-tip";');
  expect(fieldsPage.slice(fieldsOverviewIndex)).toContain("필요한 필드만 골라 보완합니다.");
  expect(fieldsPage).toContain("summary: string;");
  expect(fieldsPage.slice(fieldsOverviewIndex)).toContain('href="/contribute?tab=queue"');
  expect(fieldsPage).not.toContain("필드 선택</h2>");
  expect(fieldsPage).not.toContain("한줄 정의·도메인·업무 분류 중 하나를 선택하세요.");
  expect(fieldsPage).not.toContain("description: string;");
  expect(fieldsPage).not.toContain("detail: string;");
  expect(classificationPanel).toContain("특정 단어가 들어간 용어");
  expect(classificationPanel).toContain("AI 추천");
  expect(classificationPanel).toContain('aria-label={`${label} 보완 목록`}');
  expect(classificationPanel).not.toContain("정리</h2>");
  expect(classificationPanel).not.toContain("이 비어 있는 용어만 표시합니다");
  expect(classificationPanel).toContain("승인하고 저장");
  expect(classificationPanel).toContain("추천 버리기");
  expect(classificationPanel).toContain('{!isDomain && <th scope="col" className="w-[16%] border-b border-line px-4 py-3 font-semibold">도메인</th>}');
  expect(classificationPanel).toContain("table-fixed");
  expect(classificationPanel).not.toContain("overflow-x-auto");
  expect(classificationPanel).toContain("AI 추천 준비 중");
  expect(classificationPanel).toContain("Math.min(2, pending.length)");
  expect(definitionPanel).toContain('aria-label="한줄 정의 보완 목록"');
  expect(definitionPanel).not.toContain("LLM 한줄 정의 정리");
  expect(queueTable).toContain('<table className="w-full table-fixed border-collapse text-left text-sm">');
  expect(queueTable).toContain('<th scope="col" className="w-[30%] border-b border-line px-2 py-3 font-semibold md:w-[26%]">필요한 정보</th>');
  expect(queueTable).not.toContain(">상태</th>");
  expect(queueTable).not.toContain("StatusBadge");
  expect(queueTable).toContain("일괄 AI 검토 요청");
  expect(queueTable).not.toContain("min-w-[70rem]");
  expect(queueTable).not.toContain("overflow-x-auto");
  expect(queueTable).not.toContain('<ul className="grid gap-3 md:grid-cols-2">');
  expect(page).toContain("initialTermId={selectedTermId}");
  expect(page).toContain("totalTerms={queue.total}");
  expect(page).toContain('current="contribute" roomy>');
  expect(reviewPanel).toContain("term.id === initialTermId");
  expect(reviewPanel).toContain("AgentTermList");
  expect(reviewPanel).toContain("router.replace(`/contribute?tab=agent&termId=");
  expect(reviewPanel.indexOf("term.id === initialTermId")).toBeLessThan(reviewPanel.indexOf("const actionable"));
});
